# Generated by Django 2.1.7 on 2019-03-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat_room', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'Комната', 'verbose_name_plural': 'Комнаты'},
        ),
        migrations.AddField(
            model_name='room',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='message',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat_room.Room', verbose_name='Комната'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(blank=True, max_length=500, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='room',
            name='deleted',
            field=models.BooleanField(default=0, verbose_name='Удален'),
        ),
        migrations.AlterField(
            model_name='room',
            name='invited',
            field=models.ManyToManyField(blank=True, related_name='invited_user', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
